apiVersion: apps/v1
kind: Deployment
metadata:
  name: timelog-v2-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timelog-v2-web
  template:
    metadata:
      labels:
        app: timelog-v2-web
    spec:
      containers:
        - name: timelog-v2-web
          image: ssl1321ois/timelog_web
          imagePullPolicy: Always
          ports:
            - name: timelog-http
              containerPort: 80
